# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ~/Dileep/Blog$
email: dileepkushwaha@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
      A personal blog about technical things I find useful. Also, random ramblings and rants...

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: jekyll-dash
plugins:
  - jekyll-feed
###########################
# required by disqus to display comments
url: https://blog.dileepkushwaha.com

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging (optional)
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

dash:
  date_format: "%b %-d, %Y"


  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/dileepkush
      icon: fab fa-twitter-square
      color: cyan
#    - url: https://github.com/dileepkushwaha
#      icon: fab fa-github-square
#      color: purple
    - url: https://fosstodon.org/@dileepkushwaha
      icon: fab fa-mastodon
      color: orange
    - url: https://steamcommunity.com/id/roo00t
      icon: fab fa-steam-square
      color: green
#    - url: https://www.linkedin.com/in/kushwahadileep/
#      icon: fab fa-linkedin
#      color: purple
#    - url: https://dileepkushwaha.github.io/resume/
#      icon: fab fa-font-awesome
#      color: teal
    - url: https://keybase.io/dileepkushwaha
      icon: fab fa-keybase
      color: red
    - url: https://blog.dileepkushwaha.com/feed.xml
      icon: fa fa-rss-square
      color: orange
      
  show_author: true

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
###########################
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
plugins:
    -  jekyll/tagging
    -  liquid-md5
    -  jemoji
    - jekyll-sitemap
emoji:
  src: "https://github.githubassets.com/images/icons/"
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
keep_files: [CNAME, robots.txt, _config.yml, .git]
exclude: [_site/robots.txt, .git]
